#去申请 https://mp.weixin.qq.com/debug/cgi-bin/sandbox?t=sandbox/login
wx:
  config:
    appId: "appId"
    appSecret: "appSecret"
    templateId: "templateId"
    openidList:
      - "openid"
weather:
  config:
#    http://www:nmc:cn/rest/province/A${FJ} 城市code 查询
    city: 58847
info:
  config:
    maleName: "阿强"
    femaleName: "阿珍"
    maleBirth: "10-15"
    maleLunar: false
    femaleBirth: "09-20"
    femaleLunar: true
    togetherDate: "2022-10-14"

